# Author: @aronep6

version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      day: 'saturday'
      time: '00:00'
      interval: 'weekly'
    commit-message:
      prefix: 'chore(deps)'
    labels:
      - 'dependencies'
    assignees:
      - 'aronep6'
      - 'dependabot'