# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# Author: @aronep6

name: Check TypeScript on commit
'on':
  push:
    branches:
      - master
jobs:
  typescript-check:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18.x'

    - name: Install dependencies and check for vulnerabilities
      run: npm ci && npm audit

    - name: Run TypeScript compiler
      run: npm run ts-check


