# Author: @aronep6

name: (Check) Check TS types on push to master
"on":
  push:
    branches:
      - master
jobs:
  typescript-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies and check for typescript errors
        run: npm ci && npm run ci:typecheck
